### ISSUE TITLE
Rename this repository?

### ISSUE THREAD

**Issue by rauschma** [petehunt/react-roadmap#2]
I absolutely love the content, but I think the name “roadmap” is misleading. I expected information on upcoming versions of React. How about “React study guide”?

**Comment by petehunt** [comment]
@rauschma +1, will noodle on a better name!

**Comment by rauschma** [comment]
👍

**Comment by srameshr** [comment]
+1

**Comment by poeticninja** [comment]
React at first glance
React for beginners
Learning React
Roadmap to learning React
Getting started with React
React is awesome and you can be too.

:smile:

**Comment by gdi2290** [comment]
React from the start

**Comment by mking** [comment]
react-rampup

**Comment by HeyHugo** [comment]
:+1:  @poeticninja: "Getting started with React"

more proposals:
The React ecosystem
React ecosystem walk-through
React as a "framework"

**Comment by KleoPetroff** [comment]
How about react-walkthrough? It is after all a step-by-step learning guide.

**Comment by stecb** [comment]
I vote for @poeticninja's `learning-react`. Also `learning-react-tips` would be a good name IMHO.

**Comment by vikeen** [comment]
This article has useful information for building on your react knowledge and is not limited to beginner tutorials. Just something to keep in mind for naming.

**Comment by vga-** [comment]
React: Leveling Up. Because who doesn't want to be a level 99 react paladin.

**Comment by petehunt** [comment]
Is `react-rosetta-stone` stupid?

**Comment by wesbos** [comment]
I've used names like that in projects before and they will come after you for trademark

**Comment by rauschma** [comment]
@petehunt: Sure, why not. One more idea: `react-battle-plan`.

**Comment by petehunt** [comment]
Someone suggested `react-howto`. Goes well with my other one of these: `webpack-howto`!
